### ISSUE TITLE
Running `roc-start app` says "Failed to run generation script"

### ISSUE THREAD

**Issue by favetelinguis** [imclerran/roc-start#68]
I just built the latest master on Linux with:
`roc build src/main.roc --output roc-start --linker=legacy`

Now no matter what option or command I use I just see the help screen overview. Is this a know issue on master or am I doing something wrong?

**Comment by imclerran** [comment]
@favetelinguis, to use roc-start, you will need to supply a subcommand. If you know the the name of the platform and packages you want to use, you can run:
```sh
roc-start app platform-name package1 package2 [...]
# eg:
roc-start app basic-cli
# or
roc-start app basic-webserver roc-html roc-json
# you may also start a package by using `pkg` and omitting the platorm:
roc-start pkg package1 package2 [...]
```
If you want to choose the platform and packages from a list, run:
```
roc-start tui
```

**Comment by imclerran** [comment]
Hmm... I haven't built on Linux. I will have to check this out and see if I can reproduce. I don't experience this on MacOS. Are you also on the latest roc nightly?

**Comment by imclerran** [comment]
Okay, looks like this is related to https://github.com/roc-lang/basic-cli/issues/82. I believe if you use the surgical linker, you shouldn't have any issues.

**Comment by favetelinguis** [comment]
Yes that looks to be the issue. However I am getting this error when using other linker. Guess I am stuck until the Roc issue is fixed.

```
The surgical linker currently has issue #3609 and would fail linking your app.
Please use `--linker=legacy` to avoid the issue for now.
```

**Comment by imclerran** [comment]
Sorry to hear we're at a dead end here. Hopefully purity inference fixes this soon... 🤞

**Comment by imclerran** [comment]
This is fixed with basic-cli v0.18.0 - however, the API is in flux, with planned changes for Http request already merged. Additionally, roc-ansi, roc-json, and rvn have not yet been fully upgraded to S_C / PI / PNC. Once the dependencies have upgraded/stabilized, can begin work on upgrading roc-start to basic-cli >= v0.18.0, and this issue should be resolved.

**Comment by imclerran** [comment]
Need to verify on a Linux machine, but this should be resolved now that roc-start is using basic-cli 0.19.0.

**Comment by favetelinguis** [comment]
I did clone the roc-start repo and then I did try to compile with `roc build src/main.roc --output roc-start --linker=legacy`, running roc-start then results in Segmentation fault (core dumped). Also running ./install.sh results in seg fault.

**Comment by imclerran** [comment]
So after further investigation, I am finding that building with `--linker=surgical` will successfully build on Ubuntu 24.04, but `--optimize` must be omitted. However, the TUI app does not perform very well well without optimizations. 

I've updated the install script to fix the `#/bin/zsh` issue, `chmod +x` the file, and use `--linker=surgical` on Linux. 

If you pull down the latest main branch, you can do `./install.sh --dev` as a workaround. The CLI should still work great, but you may encounter issues in the TUI.

**Comment by favetelinguis** [comment]
Now I can compile roc-start. However if I run the TUI or any other command I always get the same error:

```
$ roc-start -v verbose app roc-ansi roc-json roc-ai:0.10.0
Creating main.roc...
Platform: roc-lang/basic-cli : 0.19.0
Packages:
| lukewilliamboswell/roc-ansi : 0.8.0
| lukewilliamboswell/roc-json : 0.12.0
| imclerran/roc-ai : v0.10.0
Failed to run generation script.
```

**Comment by imclerran** [comment]
Hmm... I can't seem to reproduce this. What is the output of:
```
ls -la ~/.cache/roc-start/scripts/roc-lang/basic-cli
```

**Comment by imclerran** [comment]
So far I haven't been able to reproduce this error. The fact that the it fails in this way means that the script was found on your system. I am wondering if the maybe it wasn't able to make the script executable due to a permissions issue....

Can you try running the same command with sudo?
```sh
sudo roc-start -v verbose app roc-ansi roc-json roc-ai:0.10.0
```

**Comment by imclerran** [comment]
It doesn't look like it would be a permissions issue, at least not with making the script executable. That should be giving you a different error message. 

I've updated a ton of the error handling around this issue - the error messages should be more descriptive now of the underlying issue. Any chance you can pull again and install, and then tell me what happens for:
```sh
roc-start app
```

**Comment by imclerran** [comment]
@favetelinguis I just added the `--no-script` flag for app generation. This will allow you to disable using platform specific scripts, in which case roc-start will fall back on using its default generation algorithm, which does not use scripts. In this case, roc-start will still generate the full header portion with all urls, but will not generate any platform specific code.

Also note that starting apps is the only thing that uses scripts. Starting packages, and upgrading both apps and packages do not depend on running any scripts.

**Comment by imclerran** [comment]
Okay, with #120, your issue should be mostly resolved. You'll still get a warning, but the app will still be generated, just without any platform specific code. You can disable the warning with the `--no-script` flag.

<img width="739" alt="Image" src="https://github.com/user-attachments/assets/ab513892-c776-43b0-aaef-289e801676c1" />

**Comment by favetelinguis** [comment]
Now it works:

```
$ roc-start -v verbose app roc-ansi roc-json roc-ai:0.10.0
Creating main.roc...
Platform: roc-lang/basic-cli : 0.19.0
Packages:
| lukewilliamboswell/roc-ansi : 0.8.0
| lukewilliamboswell/roc-json : 0.12.0
| imclerran/roc-ai : v0.10.0
| Failed to run platform script: NotFound - Using fallback instead.
Created main.roc with 3 packages ✔
```

I am using nixos and have no global install of roc so if roc-start depends on roc this will not work for me, maybe that is why it fails to run platform script (not sure what type of script that is)?

**Comment by favetelinguis** [comment]
This is the output I get

```
$ ls -la ~/.cache/roc-start/scripts/roc-lang/basic-cli
total 20
drwxr-xr-x 2 henke users 4096 12 mar 21.20 .
drwxr-xr-x 4 henke users 4096 12 mar 21.20 ..
-rw-r--r-- 1 henke users  960 12 mar 21.20 0.17.0.sh
-rw-r--r-- 1 henke users  972 12 mar 21.20 0.18.0.sh
-rwxr-xr-x 1 henke users  971 12 mar 21.20 0.19.0.sh
```

**Comment by favetelinguis** [comment]
I did some dbg printing and found a thing, look at this path to the script
`[src/main.roc:258] script_path = "/home/henke/.cache/roc-start/scripts//roc-lang/basic-cli/0.19.0.sh"` look at the double //

**Comment by imclerran** [comment]
Thanks for this! This is great - that should be an easy fix. 

Funny that chmod succeeded with the exact same path, but execution threw a fit... 🤔

**Comment by imclerran** [comment]
Alright, the double slash in the path should be resolved, and took a look to make sure nothing else might end up with any double slashes as well. Hopefully this resolves.

**Comment by favetelinguis** [comment]
I am still getting the NoFound

```
$ roc-start -v verbose app roc-ansi roc-json roc-ai:0.10.0
Creating main.roc...
Platform: roc-lang/basic-cli : 0.19.0
Packages:
| lukewilliamboswell/roc-ansi : 0.8.0
| lukewilliamboswell/roc-json : 0.12.0
| imclerran/roc-ai : v0.10.0
[src/main.roc:254] script_path = "/home/henke/.cache/roc-start/scripts/roc-lang/basic-cli/0.19.0.sh"
| Failed to run platform script: NotFound - Using fallback instead.
Created main.roc with 3 packages
```

However I can confirm that the printed path is correct and that file do exist.

**Comment by imclerran** [comment]
I think I know what the issue is - I will bet you do not have `/bin/bash`. I just updated all scripts to use `/bin/sh` instead. Assuming this is true, `roc-start update --scripts` should resolve the issue.

**Comment by imclerran** [comment]
PS: Breaking change in 0.7.0 -- I renamed "scripts" to "plugins", so anywhere that previously referenced "script" should now be replaced with "plugin": ie: `roc-start update --plugins`.

**Comment by favetelinguis** [comment]
Nice work, finally you fixed it!

```
$ roc-start -v verbose app roc-ansi roc-json roc-ai:0.10.0
Creating main.roc...
Platform: roc-lang/basic-cli : 0.19.0
Packages:
| lukewilliamboswell/roc-ansi : 0.8.0
| lukewilliamboswell/roc-json : 0.12.0
| imclerran/roc-ai : v0.10.0
Created main.roc with 3 packages ✔
```

**Comment by imclerran** [comment]
Hooray! Thanks for helping me troubleshoot! Definitely want Nix support since we have a big Nix community here!
